export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";

export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";

export const GET_TODO_LOADING = "GET_TODO_LOADING";
export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";

export const DELETE_TODO_LOADING = "DELETE_TODO_LOADING";
export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

export const UPDATE_TODO_LOADING = "UPDATE_TODO_LOADING";
export const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";

export const PENDING_TODO_LOADING = "PENDING_TODO_LOADING";
export const PENDING_TODO_SUCCESS = "PENDING_TODO_SUCCESS";
export const PENDING_TODO_ERROR = "PENDING_TODO_ERROR";

export const EDIT_TODO_LOADING = "EDIT_TODO_LOADING";
export const EDIT_TODO_SUCCESS = "EDIT_TODO_SUCCESS";
export const EDIT_TODO_ERROR = "EDIT_TODO_ERROR";

 